<a href="https://colab.research.google.com/github/yjodev/Tobigs19/blob/main/W2_Regression_%EA%B3%BC%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제 1

## Matrix 구현 
1. Linear Regression에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해주세요.

### Data Load 

In [4]:
import pandas as pd 
from google.colab import drive
drive.mount('/content/drive') 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
filepath = 'drive/MyDrive/투빅스/과제/W2_Regression/'
data = pd.read_csv(filepath + "assignment1.csv")

In [6]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [7]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [8]:
X = data.drop(["y"], axis=1)
y = data.y

In [9]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [10]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [11]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

### 1. Normal Equation

$\hat\beta = (X^T X)^-1 X^T y$

In [12]:
import numpy as np
from numpy.linalg import inv 

In [13]:
def estimate_beta(X, y):
    designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)
    # X 데이터에 첫 열의 값이 모두 1로 이루어진 Design Matrix를 만든다
    beta_hat = np.dot(np.dot(inv(np.dot(designX.T, designX)), designX.T), y)
    # Design Matrix를 이용해서 베타햇을 구한다. 
    return beta_hat

In [20]:
designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)
designX

array([[ 1.000e+00,  3.890e+01,  6.470e+01,  4.000e+00,  8.680e+02,
         5.970e+01],
       [ 1.000e+00,  4.160e+01,  4.530e+01, -4.000e+00,  9.570e+02,
         6.140e+01],
       [ 1.000e+00,  3.970e+01,  7.410e+01,  8.000e+00,  7.860e+02,
         6.100e+01],
       [ 1.000e+00,  3.730e+01,  4.800e+01,  1.900e+01,  9.840e+02,
         6.750e+01],
       [ 1.000e+00,  3.950e+01,  5.190e+01,  6.000e+00,  7.000e+02,
         5.720e+01],
       [ 1.000e+00,  3.740e+01,  5.360e+01, -5.000e+00,  1.037e+03,
         5.880e+01],
       [ 1.000e+00,  3.510e+01,  7.140e+01,  3.000e+00,  9.860e+02,
         5.860e+01],
       [ 1.000e+00,  3.880e+01,  5.830e+01,  6.000e+00,  8.190e+02,
         5.920e+01],
       [ 1.000e+00,  3.660e+01,  5.260e+01, -1.900e+01,  7.910e+02,
         5.440e+01]])

In [14]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [17]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

In [23]:
def MSE(X, y, beta_hat):
    designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)
    # X 데이터에 첫 열의 값이 모두 1로 이루어진 Design Matrix를 만든다
    y_pred = np.dot(designX, beta_hat)
    # Design Matrix와 앞 함수에서 구한 추정량 함수인 beta_hat을 곱하여 y값의 예측값으로 이루어진 행렬을 구한다.
    mse = np.sum((y - y_pred)**2) / (len(y) - (X.shape[1] + 1))
    # 실제 y값과 y예측값의 제곱을 합한 SSE를 그 자유도인 n-(p+1)로 나누어 MSE를 구한다. 
    return mse

In [22]:
MSE(X, y, estimate_beta(X, y))

4.846793168705742